### ISSUE TITLE
Cannot find /opt/soft/mysql_tools/mysqlredo/sql/sql_yacc.h

### ISSUE THREAD

**Issue by ymsu** [tom--bo/mysqlredo#13]
when I execute comand "cmake .. -DWITH_BOOST=../boost_1_77_0", an error occur
CMake Error at sql/CMakeLists.txt:1301 (MESSAGE):
  Cannot find /opt/soft/mysql_tools/mysqlredo/sql/sql_yacc.h

follow is details

#cmake .. -DWITH_BOOST=../boost_1_77_0
-- Running cmake version 3.12.3
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- This is .el7. as found from 'rpm -qf /'
-- Looking for a devtoolset compiler
-- Using /opt/rh/devtoolset-11/root/usr/bin/gcc
-- Using /opt/rh/devtoolset-11/root/usr/bin/g++
-- CMAKE_MODULE_PATH is /opt/soft/mysql_tools/mysqlredo/cmake
-- MySQL 8.0.32
-- Source directory /opt/soft/mysql_tools/mysqlredo
-- Binary directory /opt/soft/mysql_tools/mysqlredo/bld
-- CMAKE_GENERATOR: Unix Makefiles
-- SIZEOF_VOIDP 8
-- Packaging as: mysql-8.0.32-Linux-x86_64
-- Local boost dir /opt/soft/mysql_tools/mysqlredo/boost_1_77_0
-- Found /opt/soft/mysql_tools/mysqlredo/boost_1_77_0/boost/version.hpp 
-- BOOST_VERSION_NUMBER is #define BOOST_VERSION 107700
-- BOOST_INCLUDE_DIR /opt/soft/mysql_tools/mysqlredo/boost_1_77_0
-- NUMA library missing or required version not available
-- ZLIB_VERSION (bundled) is 1.2.13
-- ZLIB_INCLUDE_DIR /opt/soft/mysql_tools/mysqlredo/extra/zlib/zlib-1.2.13
-- ZLIB_LIBRARY zlib
-- ZSTD_LEGACY_SUPPORT not defined!
-- ZSTD_VERSION (bundled) is 1.5.0
-- ZSTD_INCLUDE_DIR /opt/soft/mysql_tools/mysqlredo/extra/zstd/zstd-1.5.0/lib
-- ZSTD_LIBRARY zstd
-- OPENSSL_VERSION (system) is 1.00.02
-- The openssl command does support zlib
-- OPENSSL_INCLUDE_DIR = /usr/include
-- OPENSSL_LIBRARY = /usr/lib64/libssl.so
-- CRYPTO_LIBRARY = /usr/lib64/libcrypto.so
-- OPENSSL_LIB_DIR = 
-- OPENSSL_VERSION_MAJOR = 1
-- OPENSSL_VERSION_MINOR = 00
-- OPENSSL_FIX_VERSION = 02
-- SSL_LIBRARIES = /usr/lib64/libssl.so;/usr/lib64/libcrypto.so;dl
-- KERBEROS path is none, disabling kerberos support.
-- HAVE_KRB5_KRB5_H  
-- KERBEROS_LIBRARIES  
CMake Warning at cmake/sasl.cmake:273 (MESSAGE):
  Could not find SASL
Call Stack (most recent call first):
  CMakeLists.txt:1786 (MYSQL_CHECK_SASL)

CMake Warning at cmake/ldap.cmake:158 (MESSAGE):
  Could not find LDAP
Call Stack (most recent call first):
  CMakeLists.txt:1790 (MYSQL_CHECK_LDAP)

-- AWK_EXECUTABLE is /usr/bin/gawk
-- Found Git: /usr/bin/git  
-- LIBEVENT_VERSION (bundled) 2.1.11
-- LIBEVENT_INCLUDE_DIRS /opt/soft/mysql_tools/mysqlredo/extra/libevent/libevent-2.1.11-stable/include;/opt/soft/mysql_tools/mysqlredo/bld/extra/libevent/libevent-2.1.11-stable/include
-- LIBEVENT_LIBRARIES event_core;event_extra;event_openssl;event_pthreads
-- LZ4_VERSION (bundled) is 1.9.4
-- LZ4_INCLUDE_DIR /opt/soft/mysql_tools/mysqlredo/extra/lz4/lz4-1.9.4/lib
-- LZ4_LIBRARY lz4_lib
-- ICU_VERSION (bundled) is 69
-- ICU_INCLUDE_DIRS /opt/soft/mysql_tools/mysqlredo/extra/icu/icu-release-69-1/source/common;/opt/soft/mysql_tools/mysqlredo/extra/icu/icu-release-69-1/source/stubdata;/opt/soft/mysql_tools/mysqlredo/extra/icu/icu-release-69-1/source/i18n
-- ICU_LIBRARIES icui18n;icuuc;icustubdata
-- PROTOBUF_VERSION (bundled) is 3.19.4
-- PROTOBUF_INCLUDE_DIR /opt/soft/mysql_tools/mysqlredo/extra/protobuf/protobuf-3.19.4/src
-- PROTOBUF_LIBRARY libprotobuf
-- PROTOBUF_LITE_LIBRARY libprotobuf-lite
-- PROTOBUF_PROTOC_EXECUTABLE protoc
-- WITH_CURL=none, not using any curl library.
-- CURL_LIBRARY = 
-- CURL_INCLUDE_DIR = 
-- RAPIDJSON_INCLUDE_DIR /opt/soft/mysql_tools/mysqlredo/extra/rapidjson/include
-- RAPIDJSON_MAJOR_VERSION is 1
-- RAPIDJSON_MINOR_VERSION is 1
-- UDEV_SYSTEM_LIBRARY /usr/lib64/libudev.so
-- FIDO_VERSION (bundled) is 1.8.0
-- FIDO_INCLUDE_DIR /opt/soft/mysql_tools/mysqlredo/extra/libfido2/libfido2-1.8.0/src
-- FIDO_LIBRARY fido2
-- CMAKE_MODULE_LINKER_FLAGS_DEBUG  -Wl,-rpath,'$ORIGIN/../../private'
-- CMAKE_SHARED_LINKER_FLAGS_DEBUG  -Wl,-rpath,'$ORIGIN/../../private'
-- Found Unix DNS SRV APIs
-- Skipping the LDAP client authentication plugin
-- Skipping FIDO client authentication plugin.
-- Skipping the KERBEROS client authentication plugin.
-- Skipping the OCI authentication client plugin.
-- Library mysqlclient depends on OSLIBS -lpthread;m;rt;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;dl
-- MERGE_CONVENIENCE_LIBRARIES TARGET mysqlclient
-- MERGE_CONVENIENCE_LIBRARIES LIBS clientlib;mytime;strings;vio;mysys;zlib;zstd
-- Building ndbcluster plugin
-- Excluding Cluster Java components
-- LIBS_TO_MERGE mysys;mytime;ndbapi;ndbgeneral;ndblogger;ndbmgmapi;ndbmgmcommon;ndbportlib;ndbsignaldata;ndbtrace;ndbtransport;strings;zlib
-- Library ndbclient_static depends on OSLIBS -lpthread;m;rt;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;dl
-- MERGE_CONVENIENCE_LIBRARIES TARGET ndbclient_static
-- MERGE_CONVENIENCE_LIBRARIES LIBS mysys;mytime;ndbapi;ndbgeneral;ndblogger;ndbmgmapi;ndbmgmcommon;ndbportlib;ndbsignaldata;ndbtrace;ndbtransport;strings;zlib
-- RPC_INCLUDE_DIRS /usr/include
-- MYSQLX - Text log of protobuf messages enabled
-- Library json_binlog_static depends on OSLIBS -lpthread;m;rt;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;dl
-- MERGE_CONVENIENCE_LIBRARIES TARGET json_binlog_static
-- MERGE_CONVENIENCE_LIBRARIES LIBS json_client_library;mysys;mytime;strings
CMake Error at sql/CMakeLists.txt:1301 (MESSAGE):
  Cannot find /opt/soft/mysql_tools/mysqlredo/sql/sql_yacc.h

-- Configuring incomplete, errors occurred!
See also "/opt/soft/mysql_tools/mysqlredo/bld/CMakeFiles/CMakeOutput.log".
See also "/opt/soft/mysql_tools/mysqlredo/bld/CMakeFiles/CMakeError.log".

**Comment by tom--bo** [comment]
Thank you so much for your report.
Hmm, could you check `/opt/soft/mysql_tools/mysqlredo/sql/sql_yacc.h` file? Doesn't the file really exist?

**Comment by ymsu** [comment]
file sql/sql_yacc.h is not exist, there hava a sql_yacc.yy, This problem may be caused by bison. I tried versions 2.1 and 3.8, and the error disappeared. However, when executing the command make mysqlredo, the following error appeared around 63%. I suspect that the problem is caused by the bison version.

#make mysqlredo
[  2%] Built target zlib_objlib
[  2%] Built target zlib
[  6%] Built target libprotobuf
[ 10%] Built target libprotoc
[ 10%] Built target protoc
[ 10%] Built target rpl_protobuf_lite
[ 10%] Built target lz4_lib
[ 12%] Built target zstd_objlib
[ 12%] Built target zstd
[ 12%] Built target event_core
[ 12%] Built target event_extra
[ 12%] Built target event_openssl
[ 12%] Built target event_pthreads
[ 20%] Built target icui18n
[ 20%] Built target icustubdata
[ 28%] Built target icuuc
[ 28%] Built target libprotobuf-lite
[ 32%] Built target mysys_objlib
[ 32%] Built target uca9dump
[ 34%] Built target strings_objlib
[ 34%] Built target mytime_objlib
[ 34%] Built target mytime
[ 34%] Built target mysys
[ 34%] Built target strings
[ 34%] Built target vio_objlib
[ 34%] Built target vio
[ 34%] Built target comp_err
[ 34%] Built target GenError
[ 34%] Built target binlogevents_static
[ 34%] Built target archive
[ 36%] Built target blackhole
[ 36%] Built target csv
[ 36%] Built target federated
[ 36%] Built target heap_library
[ 36%] Built target heap
[ 36%] Built target all_sys_schema
[ 36%] Built target comp_sql
[ 36%] Built target sql_commands
[ 36%] Built target GenSysSchema
[ 38%] Built target myisam_library
[ 38%] Built target myisam
[ 38%] Built target myisammrg
[ 40%] Built target ndbapi_objlib
[ 40%] Built target ndbapi
[ 40%] Built target ndbportlib_objlib
[ 40%] Built target ndbportlib
[ 40%] Built target ndbmgmapi_objlib
[ 40%] Built target ndbtrace_objlib
[ 44%] Built target ndbsignaldata_objlib
[ 44%] Built target ndbsignaldata
[ 46%] Built target ndbgeneral_objlib
[ 46%] Built target ndblogger_objlib
[ 48%] Built target ndbmgmcommon_objlib
[ 48%] Built target ndbmgmapi
[ 48%] Built target ndbmgmcommon
[ 48%] Built target ndblogger
[ 48%] Built target ndbgeneral
[ 48%] Built target ndbtrace
[ 48%] Built target ndbtransport_objlib
[ 48%] Built target ndbtransport
[ 48%] Built target ndbclient_static
[ 51%] Built target ndbcluster
[ 57%] Built target perfschema
[ 57%] Built target temptable
[ 57%] Built target ngram_parser
[ 57%] Built target GenLiteProtos
[ 59%] Built target mysqlxmessages_lite
[ 59%] Built target mysqlxmessages
[ 59%] Built target xprotocol_plugin
[ 59%] Built target xprotocol_tags
[ 63%] Built target mysqlx
[ 63%] Built target gen_lex_hash
[ 63%] Built target GenServerSource
[ 63%] Building CXX object sql/CMakeFiles/gen_keyword_list.dir/gen_keyword_list.cc.o
In file included from /opt/soft/mysql_tools/mysqlredo/sql/lex.h:36,
                 from /opt/soft/mysql_tools/mysqlredo/sql/gen_keyword_list.cc:40:
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_hints.yy.h:174:22: error: ‘YYSTYPE’ was not declared in this scope
  174 | int HINT_PARSER_lex (YYSTYPE *yylvalp, class Hint_scanner *scanner);
      |                      ^~~~~~~
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_hints.yy.h:174:31: error: ‘yylvalp’ was not declared in this scope
  174 | int HINT_PARSER_lex (YYSTYPE *yylvalp, class Hint_scanner *scanner);
      |                               ^~~~~~~
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_hints.yy.h:174:40: error: expected primary-expression before ‘class’
  174 | int HINT_PARSER_lex (YYSTYPE *yylvalp, class Hint_scanner *scanner);
      |                                        ^~~~~
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_hints.yy.h:174:67: error: expression list treated as compound expression in initializer [-fpermissive]
  174 | int HINT_PARSER_lex (YYSTYPE *yylvalp, class Hint_scanner *scanner);
      |                                                                   ^
In file included from /opt/soft/mysql_tools/mysqlredo/sql/lex.h:37,
                 from /opt/soft/mysql_tools/mysqlredo/sql/gen_keyword_list.cc:40:
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_yacc.h:1686:15: error: ‘YYSTYPE’ was not declared in this scope; did you mean ‘YYLTYPE’?
 1686 | int MYSQLlex (YYSTYPE *yylvalp, YYLTYPE *yyllocp, class THD *YYTHD);
      |               ^~~~~~~
      |               YYLTYPE
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_yacc.h:1686:24: error: ‘yylvalp’ was not declared in this scope
 1686 | int MYSQLlex (YYSTYPE *yylvalp, YYLTYPE *yyllocp, class THD *YYTHD);
      |                        ^~~~~~~
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_yacc.h:1686:41: error: expected primary-expression before ‘*’ token
 1686 | int MYSQLlex (YYSTYPE *yylvalp, YYLTYPE *yyllocp, class THD *YYTHD);
      |                                         ^
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_yacc.h:1686:42: error: ‘yyllocp’ was not declared in this scope
 1686 | int MYSQLlex (YYSTYPE *yylvalp, YYLTYPE *yyllocp, class THD *YYTHD);
      |                                          ^~~~~~~
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_yacc.h:1686:51: error: expected primary-expression before ‘class’
 1686 | int MYSQLlex (YYSTYPE *yylvalp, YYLTYPE *yyllocp, class THD *YYTHD);
      |                                                   ^~~~~
/opt/soft/mysql_tools/mysqlredo/bld/sql/sql_yacc.h:1686:67: error: expression list treated as compound expression in initializer [-fpermissive]
 1686 | int MYSQLlex (YYSTYPE *yylvalp, YYLTYPE *yyllocp, class THD *YYTHD);
      |                                                                   ^
make[3]: *** [sql/CMakeFiles/gen_keyword_list.dir/gen_keyword_list.cc.o] Error 1
make[2]: *** [sql/CMakeFiles/gen_keyword_list.dir/all] Error 2
make[1]: *** [client/CMakeFiles/mysqlredo.dir/rule] Error 2
make: *** [mysqlredo] Error 2

**Comment by ymsu** [comment]
The problem was solved. It was a problem with the bison version. I tried bison version 2.7 and it compiled normally.
